### ISSUE TITLE
livepeer release

### ISSUE THREAD

**Issue by pedrompcaetano** [livepeer/catalyst-uploader#78]
Is it possible to build and publish a new release?
The available binary is a bit dated, and there are a few commits that would enhance end user experience. (exponential upload timeouts)

Thank you

**Comment by thomshutt** [comment]
@pedrompcaetano Of course! Done: https://github.com/livepeer/catalyst-uploader/releases/tag/v0.1.7

**Comment by pedrompcaetano** [comment]
Thank you! <3
